/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EventData } from "./EventData";
import { EventDataCountArgs } from "./EventDataCountArgs";
import { EventDataFindManyArgs } from "./EventDataFindManyArgs";
import { EventDataFindUniqueArgs } from "./EventDataFindUniqueArgs";
import { DeleteEventDataArgs } from "./DeleteEventDataArgs";
import { EventDataService } from "../eventData.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EventData)
export class EventDataResolverBase {
  constructor(
    protected readonly service: EventDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EventData",
    action: "read",
    possession: "any",
  })
  async _eventDataItemsMeta(
    @graphql.Args() args: EventDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EventData])
  @nestAccessControl.UseRoles({
    resource: "EventData",
    action: "read",
    possession: "any",
  })
  async eventDataItems(
    @graphql.Args() args: EventDataFindManyArgs
  ): Promise<EventData[]> {
    return this.service.eventDataItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EventData, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EventData",
    action: "read",
    possession: "own",
  })
  async eventData(
    @graphql.Args() args: EventDataFindUniqueArgs
  ): Promise<EventData | null> {
    const result = await this.service.eventData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EventData)
  @nestAccessControl.UseRoles({
    resource: "EventData",
    action: "delete",
    possession: "any",
  })
  async deleteEventData(
    @graphql.Args() args: DeleteEventDataArgs
  ): Promise<EventData | null> {
    try {
      return await this.service.deleteEventData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
