/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Guild } from "./Guild";
import { GuildCountArgs } from "./GuildCountArgs";
import { GuildFindManyArgs } from "./GuildFindManyArgs";
import { GuildFindUniqueArgs } from "./GuildFindUniqueArgs";
import { DeleteGuildArgs } from "./DeleteGuildArgs";
import { GuildService } from "../guild.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Guild)
export class GuildResolverBase {
  constructor(
    protected readonly service: GuildService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Guild",
    action: "read",
    possession: "any",
  })
  async _guildsMeta(
    @graphql.Args() args: GuildCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Guild])
  @nestAccessControl.UseRoles({
    resource: "Guild",
    action: "read",
    possession: "any",
  })
  async guilds(@graphql.Args() args: GuildFindManyArgs): Promise<Guild[]> {
    return this.service.guilds(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Guild, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Guild",
    action: "read",
    possession: "own",
  })
  async guild(
    @graphql.Args() args: GuildFindUniqueArgs
  ): Promise<Guild | null> {
    const result = await this.service.guild(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Guild)
  @nestAccessControl.UseRoles({
    resource: "Guild",
    action: "delete",
    possession: "any",
  })
  async deleteGuild(
    @graphql.Args() args: DeleteGuildArgs
  ): Promise<Guild | null> {
    try {
      return await this.service.deleteGuild(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
